feat: add scene loader ktx support
ant-galaxy/oasis-engine pull request #1242
Opened 2022-12-05 07:28 UTC by gz65555

### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior (if this is a feature change)?

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

### Other information:

2022-12-05 08:17 UTC, zhuxudong requested changes

2022-12-05 08:17 UTC, zhuxudong commented on packages/loader/src/gltf/parser/TextureParser.ts
> +            const type = uri.endsWith(".ktx") ? AssetType.KTX : AssetType.Texture2D;
"**.ktx?sfds"

2022-12-05 09:06 UTC, GuoLei1990 approved these changes

2022-12-06 07:49 UTC, zhuxudong approved these changes
+1

2022-12-08 07:42 UTC, merged